Server:
  port: 8001
  host: 'localhost'
  publicKey: 'AABB-CCDD-112233'
  staticPath: "./stub"
  uploadPath: "./stub/res"
  temp: "./stub/temp"
DB:
  port: 3306
  host: '0.0.0.0'
  type: 'Mysql'
  prefix: "msj_"
  user: "root"
  password: "b6a1a07edd14c8460ec866a2b6af19ff"
  dataBase: "sso"
  sourcePath: "./stub/dataSource"
Log:
  level: debug
Email:
  pop3: pop.163.com
  smtp: smtp.163.com
  imap: imap.163.com
  user: "elmer_mo@163.com"
  accessKey: RLYWSLIXMGDHWGMO