Server:
  port: 8000
  host: 'localhost'
  publicKey: 'AABB-CCDD-112233'
  staticPath: "./stub"
DB:
  port: 3306
  host: '0.0.0.0'
  type: 'Mysql'
  prefix: "msj_"
  user: "root"
  password: "b6a1a07edd14c8460ec866a2b6af19ff"
  dataBase: "sso"
  sourcePath: "./stub/dataSource"
Log:
  level: debug